# https://yarnpkg.com/configuration/yarnrc

# `yarn add foo` としたとき "foo": "1.0.3" のようにデフォルトで exact version を指定する。
defaultSemverRangePrefix: ''

# デフォルトは pnp だが、引き続き node_modules を利用するため "node-modules" を指定する。
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.3.cjs
