packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  core-js: false
  esbuild: true
  lefthook: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@wakamsha/eslint-config'
  - '@wakamsha/oxlint-config'
