name: Setup Node.js Environment
description: Sets up Node.js environment with pnpm

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.2.0

    - name: Setup node version
      uses: actions/setup-node@v6
      with:
        node-version-file: ./.node-version
        cache: pnpm

    - name: install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
