name: Restore Node.js env
description: Node.js によるタスクランナー基盤を復元する

runs:
  using: 'composite'
  steps:
    - name: Setup node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ./.node-version

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.2.0

    - name: cache node_modules
      uses: actions/cache@v5
      with:
        path: |
          ./node_modules
          ./apps/*/node_modules
          ./packages/*/node_modules
        key: node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: install node_modules
      shell: bash
      run: pnpm install --frozen-lockfile
