export function template(storySpec) {
  return `
/* eslint-disable no-template-curly-in-string */
/*
* NOTE: This class is auto generated by /wakamsha/learn-react/packages/catalog
* Do not edit the class manually.
*/

export const storySpec = ${JSON.stringify(storySpec, null, 2)} as const;
`;
}
