module.exports = ({ importItems, storyTree }) => `
/*
* NOTE: This class is auto generated by /wakamsha/learn-react/packages/catalog
* Do not edit the class manually.
*/
${importItems.map(({ path, storyName }) => `import { Story as ${storyName} } from '${path}';`).join(`\n`)}

type Stories = {
  [subPackage: string]: {
    [type: string]:
      | {
          [category: string]: {
            [story: string]: () => JSX.Element;
          };
        }
      | {
          [story: string]: () => JSX.Element;
        };
  };
};

export const stories: Stories = {
  ${storyTree.map(
    package =>
      `${package.name}: {
        ${package.children.map(
          type =>
            `${type.name}: {
              ${type.children.map(({ name, children }) =>
                children
                  ? `${name}: {
                    ${children.map(category => `${category.name}`)}
                  }`
                  : `${name}`,
              )}
            }`,
        )}
      }`,
  )}
};
`;
