export function template({ importPaths, storyTree }) {
  return `
/*
 * NOTE: This class is auto generated by /wakamsha/learn-react/packages/catalog
 * Do not edit the class manually.
 */
${importPaths
  .map(
    path => `import { Story as ${path.split('/').map(pascalCase).join('')} } from '@learn-react/${path}/index.story';`,
  )
  .join(`\n`)}

  export const stories = {
    ${storyTree.map(item => makeTree(item))}
  };
  `;
}

function makeTree({ name, children }, prefix = '') {
  const optimizedName = `${prefix}${pascalCase(name)}`;

  return children
    ? `${name}: { ${children.map(subPackage => makeTree(subPackage, optimizedName))} }`
    : `${name}: ${optimizedName}`;
}

function pascalCase(str) {
  return `-${str.replace(/_/g, '-')}`.replace(/-(\w)/g, (_, m) => m.toUpperCase());
}
