name: Check @learn-react/features

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/features/**"

jobs:
  check_features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Initialize
        uses: ./.github/actions/restore-node

      - name: Lint
        run: pnpm features lint

      - name: Test
        run: pnpm features test
