# Labeler which adds tags to PR automatically based on .github/labeler.yml

name: Pull Request Labeler

on:
  pull_request:
    types: [opened, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
