# PR 差分にあるファイルの影響を受けるファイルを洗い出す。

name: Module Graph

on:
  pull_request:
    branches:
      - '*'

jobs:
  analytics:
    # needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            *.ts
            *.tsx

      - name: List all modified files
        if: github.event.number
        run: |
          echo ${{ steps.changed-files.outputs.all_modified_files }}
