# @learn-react/catalog の JavaScript ファイルサイズ情報を Artifacts として保存する。

name: Save file size info in main branch

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Print node version
        run: node -v

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: yarn

  save_file_size_info:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV

      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Build icon data
        run: yarn icon build

      - name: Build
        run: yarn catalog build

      - name: Export file size info
        uses: actions/github-script@v6
        with:
          script: |
            const run = require('./.github/workflows/bin/exportFileSizeInfo.js');
            run({
              exportPath: './fileSizeInfo.json',
              targetPathPattern: './packages/catalog/dist/assets/{index,vendor}.*.js',
            })

      - uses: actions/upload-artifact@v3
        with:
          name: fileSizeInfo
          path: ./fileSizeInfo.json
