// @ts-check

export function template(src) {
  return `
/*
* NOTE: This class is auto generated by /wakamsha/learn-react/packages/icon
* Do not edit the class manually.
*/
export type IconName = ${src.map(({ key }) => `'${key}'`).join(' | ')};

export type IconElements = Readonly<{ [name in IconName]: JSX.Element }>;

export const iconElements: IconElements = {
  ${src.map(({ key, value }) => `'${key}': (${value})`)}
};
  `;
}
